### ISSUE TITLE
Pre-lock custom hook per layer

### ISSUE THREAD

**Issue by neilmehta24** [lmstudio-ai/venvstacks#105]
There are actions that we always need to take prior to locking a specific layer that we have. For example, when re-locking one of our application layers, we want to rebuild one of our wheels from source beforehand. It would be nice if we could specify that command in the layer `toml` like so.

```toml
[[applications]]
name="src"
...
pre-lock-hook="/path/to/python -m build relative/path/to/src"
```
